---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  labels:
    app: grpc-server
spec:
  clusterIP: None  # This makes the service "headless"
  selector:
    app: grpc-server
  ports:
  - name: grpc
    port: 5000
    targetPort: 5000
  - name: metrics
    port: 8080
    targetPort: 8080
